apiVersion: "pipelinesascode.tekton.dev/v1alpha1"
kind: Repository
metadata:
  name: bag9l0olr-java-springboot-gitops-repository
spec:
  url: https://github.com/rhtap-rhdh-qe/bag9l0olr-java-springboot-gitops